//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Web.Kiosk.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gizmo.Web.Kiosk.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to server. Retrying....
        /// </summary>
        public static string ERROR_CONNECTION {
            get {
                return ResourceManager.GetString("ERROR_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hosts found. Please check layout configuration..
        /// </summary>
        public static string ERROR_NO_HOSTS {
            get {
                return ResourceManager.GetString("ERROR_NO_HOSTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hosts found..
        /// </summary>
        public static string ERROR_NO_HOSTS_FOUND {
            get {
                return ResourceManager.GetString("ERROR_NO_HOSTS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string HOST_STATE_FREE {
            get {
                return ResourceManager.GetString("HOST_STATE_FREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In use.
        /// </summary>
        public static string HOST_STATE_IN_USE {
            get {
                return ResourceManager.GetString("HOST_STATE_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string HOST_STATE_LOCKED {
            get {
                return ResourceManager.GetString("HOST_STATE_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string HOST_STATE_MAINTENANCE {
            get {
                return ResourceManager.GetString("HOST_STATE_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of order.
        /// </summary>
        public static string HOST_STATE_OUT_OF_ORDER {
            get {
                return ResourceManager.GetString("HOST_STATE_OUT_OF_ORDER", resourceCulture);
            }
        }

        public static string USER_GUEST {
            get { return ResourceManager.GetString("USER_GUEST", resourceCulture); }
        }

        public static string TOOLTIP_ONLINE {
            get { return ResourceManager.GetString("TOOLTIP_ONLINE", resourceCulture); }
        }

        public static string TOOLTIP_OFFLINE {
            get { return ResourceManager.GetString("TOOLTIP_OFFLINE", resourceCulture); }
        }

        public static string TOOLTIP_LOCKED {
            get { return ResourceManager.GetString("TOOLTIP_LOCKED", resourceCulture); }
        }

        public static string TOOLTIP_OUT_OF_ORDER {
            get { return ResourceManager.GetString("TOOLTIP_OUT_OF_ORDER", resourceCulture); }
        }

        public static string TOOLTIP_MAINTENANCE {
            get { return ResourceManager.GetString("TOOLTIP_MAINTENANCE", resourceCulture); }
        }

        public static string TOOLTIP_NO_SESSIONS {
            get { return ResourceManager.GetString("TOOLTIP_NO_SESSIONS", resourceCulture); }
        }

        public static string TOOLTIP_LEFT {
            get { return ResourceManager.GetString("TOOLTIP_LEFT", resourceCulture); }
        }

        public static string SESSION_STATE_ACTIVE {
            get { return ResourceManager.GetString("SESSION_STATE_ACTIVE", resourceCulture); }
        }

        public static string SESSION_STATE_PAUSED {
            get { return ResourceManager.GetString("SESSION_STATE_PAUSED", resourceCulture); }
        }

        public static string SESSION_STATE_PENDING {
            get { return ResourceManager.GetString("SESSION_STATE_PENDING", resourceCulture); }
        }

        public static string SESSION_STATE_GRACE {
            get { return ResourceManager.GetString("SESSION_STATE_GRACE", resourceCulture); }
        }
    }
}
